import path from 'path';
import { execFileSync } from 'child_process';
import { existsSync, unlinkSync } from 'fs';
import { slugify } from '../../../scripts/lib/slug.js';
import { requireNoActiveStage } from '../../../scripts/lib/stage-guard.js';
import { makeIO } from './helpers.js';

const WORK_FILES = ['WORK.md', 'WORK.history.yaml', 'WORK.feedback.yaml'];

export function createGitTools({ tool }) {
  return {
    foundry_git_branch: tool({
      description: 'Create and checkout a work branch for a flow',
      args: {
        flowId: tool.schema.string().describe('Flow ID'),
        description: tool.schema.string().describe('Branch description suffix'),
      },
      async execute(args, context) {
        const io = makeIO(context.worktree);
        const guard = requireNoActiveStage(io);
        if (!guard.ok) return JSON.stringify({ error: `foundry_git_branch ${guard.error}` });
        const flowSlug = slugify(args.flowId);
        const descSlug = slugify(args.description);
        const branch = `work/${flowSlug}-${descSlug}`;
        try {
          execFileSync('git', ['checkout', '-b', branch], { cwd: context.worktree, encoding: 'utf8', stdio: 'pipe' });
        } catch (err) {
          const stderr = (err && (err.stderr || err.stdout)) ? String(err.stderr || err.stdout).trim() : '';
          return JSON.stringify({
            error: `foundry_git_branch: failed to create branch '${branch}'.${stderr ? ' ' + stderr : ''}`,
          });
        }
        return JSON.stringify({ ok: true, branch });
      },
    }),

    foundry_git_finish: tool({
      description: 'Clean up work files, squash merge to base branch, and delete the work branch (requires confirm:true)',
      args: {
        message: tool.schema.string().describe('Squash merge commit message'),
        baseBranch: tool.schema.string().optional().describe('Target branch (default: main)'),
        confirm: tool.schema.boolean().optional().describe('Must be true to perform destructive operations; otherwise returns a plan'),
      },
      async execute(args, context) {
        const io = makeIO(context.worktree);
        const guard = requireNoActiveStage(io);
        if (!guard.ok) return JSON.stringify({ error: `foundry_git_finish ${guard.error}` });
        const base = args.baseBranch || 'main';
        const cwd = context.worktree;
        const opts = { cwd, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] };

        // Get current branch name
        const workBranch = execFileSync('git', ['branch', '--show-current'], opts).trim();

        // Already on base — graceful no-op (nothing to merge from).
        if (workBranch === base) {
          return JSON.stringify({
            ok: true,
            noop: true,
            message: `Already on ${base} — nothing to merge`,
            branch: base,
          });
        }

        // Compute planned side effects.
        const filesToDelete = WORK_FILES.filter((f) => existsSync(path.join(cwd, f)));
        const planned = {
          workBranch,
          baseBranch: base,
          filesToDelete,
          action: 'delete-work-files, commit-cleanup, checkout-base, squash-merge, commit, delete-work-branch',
          commitMessage: args.message,
        };

        // Confirmation gate.
        if (args.confirm !== true) {
          return JSON.stringify({
            ok: false,
            error: 'foundry_git_finish requires {confirm: true} to perform destructive operations. Re-invoke with confirm:true to apply the plan.',
            planned,
          });
        }

        // Refuse dirty worktree (tracked-file modifications). Untracked files
        // are tolerated — they survive checkout/merge and are commonly produced
        // by tooling (e.g. .gitignore generated by plugin loading).
        const dirty = execFileSync('git', ['status', '--porcelain', '--untracked-files=no'], opts).trim();
        if (dirty) {
          const dirtyFiles = dirty.split('\n').map((line) => line.slice(3));
          return JSON.stringify({
            ok: false,
            error: 'foundry_git_finish refuses to run on a dirty worktree (uncommitted changes to tracked files). Commit or stash them first.',
            dirty: dirtyFiles,
          });
        }

        // Delete work files
        for (const f of filesToDelete) {
          const p = path.join(cwd, f);
          if (existsSync(p)) unlinkSync(p);
        }

        // Commit cleanup if there are changes
        try {
          execFileSync('git', ['add', '-A'], opts);
          const status = execFileSync('git', ['status', '--porcelain'], opts).trim();
          if (status) {
            const cleanupMsg = `[${workBranch.replace('work/', '')}] cleanup: remove work files`;
            execFileSync('git', ['commit', '-m', cleanupMsg], opts);
          }
        } catch { /* no changes to commit */ }

        // Switch to base and squash merge. Abort on conflict.
        execFileSync('git', ['checkout', base], opts);
        try {
          execFileSync('git', ['merge', '--squash', workBranch], opts);
        } catch (err) {
          // Abort the failed merge so the index/worktree is restored.
          try { execFileSync('git', ['reset', '--hard', 'HEAD'], opts); } catch { /* best-effort */ }
          // Return to the work branch so the caller can resolve.
          try { execFileSync('git', ['checkout', workBranch], opts); } catch { /* best-effort */ }
          const stderr = (err && (err.stderr || err.stdout)) ? String(err.stderr || err.stdout).trim() : '';
          return JSON.stringify({
            ok: false,
            error: `foundry_git_finish: squash merge failed (likely a conflict). Work branch '${workBranch}' preserved.${stderr ? ' ' + stderr : ''}`,
          });
        }

        execFileSync('git', ['commit', '-m', args.message], opts);
        const hash = execFileSync('git', ['rev-parse', '--short', 'HEAD'], opts).trim();

        // Force-delete work branch (required after squash)
        execFileSync('git', ['branch', '-D', workBranch], opts);

        return JSON.stringify({ ok: true, hash, branch: base });
      },
    }),
  };
}
